### ISSUE TITLE
tagBrowse Issue: in doPost??TypeError: str indices must be integers

### ISSUE THREAD

**Issue by Holomew** [JoshMcguigan/ignition-web-scripts#2]
I keep getting an error on the browseTags line of the tagBrowse file.

Maybe something has changed with the parameters in the browseTags function? Is this code for the latest version of Ignition (7.9)?

**Comment by Holomew** [comment]
I think I found the problem to this if anyone else is experiencing this. It seems like the Python/Jython layer is adding the letter "u" in the JSON data to signify it is unicode, which is fine except that in this is being put in the wrong place. The "u" us being put in front of the VALUE instead of the key (where it should be) when sending JSON to a doGet Python resource file.

I've tested this by hardcoding the JSON and the decoding works fine when the "u" is placed where it should be like so: {u'parentPath': '[Root Path]Directory/Directory/'} , instead of Ignition is doing which is: {'parentPath': u'[Root Path]Directory/Directory/'}

When system.utl.jsondecode tries to decode the JSON with the "u" in the incorrect place, it is causing this str indices error.

I have no solution on how to rectify this as I'm not aware of a way to strip or replace the character at that layer.

**Comment by JoshMcguigan** [comment]
This code was written for Ignition version 7.9. [This blog post](http://info.vertech.com/blog/build-a-front-end-web-app-for-ignition-scada-using-react-and-the-web-dev-module) has a link to download the original gateway backup which already has these scripts setup, so you could try that. 

Also be sure you are setting the content-type and body of the message as described in the readme file of this repo. How are you sending the HTTP request to Ignition to test this? 

 Edit - I just realized you closed this issue. Did you figure it out?

**Comment by Holomew** [comment]
Thanks for replying. Unfortunately, still getting the same issues. Have tried testing a doGet as well and that had some of its own issues.

I've been at it for quite some time and there is something unusual going on but not quite sure I've narrowed it down. I believe it may have something to do with when Ignition is translating the incoming JSON in the Python/Jython and adding the "u" unicode character in the wrong spot (adding it in front of the value instead of the key, e.g.: "{key: u value}" instead of "{u key: value}".

It has been pretty frustrating for something easy and elegant as you've written. Is it possible it's an evaluation-only license/version issue because I'm noticing other strange things like not even getting an external stylesheet to load.

Edit: Really, the bottom line here is that I cannot get code to come over properly formatted to make system.tag.browseTags work. That is the entire issue. I can hard code "system.tag.browseTags(parentPath="[myTagProvider]Directory/Directory/etc")" and that works fine. And I can get JSON to come over seemingly okay with a few tricks and that outputs fine. But something is happening when decoding it maybe that is just not working for that function.

**Comment by JoshMcguigan** [comment]
I was running this under an evaluation license, so I don't think that would be the issue. I'd guess the issue is related to how you are sending the request data. 

How are you sending the POST request for testing? You'll need to make sure the content-type header is set to text/plain as mentioned in the readme. I suspect that is your issue, as most HTTP clients would probably set the content-type to application/JSON when sending a JSON payload.

**Comment by Holomew** [comment]
I should have specified the issues I was having with the misplaced "u" was when testing GET (only because I couldn't get POST to work), but POST was written as the example stated: sending an ajax call (with jQuery) contentType text/plain. One thing I wasn't certain about was your use of 'rootPath'. I tried various ways with and without it (both in the call and in the action/handling python page) as the system.tag.browseTags function actually takes 'parentPath' as the key for the argument/parameter. Regardless, I would still get the above error (TypeError: str indices must be integers) in that function.

**Comment by JoshMcguigan** [comment]
I suspect the issue is related to how jQuery is sending the request. You may want to try one of the two repositories below. The first one is just a set of simple React components to interface with these scripts, and the second one is a full example application. 

https://github.com/JoshMcguigan/ignition-web-hoc
https://github.com/JoshMcguigan/ignition-web-example

But you'll definitely need to send 'rootPath' in the request, because the Ignition script expects that. The error sounds like what you would get if you were just sending the tag paths as a string, instead of as an object with the 'rootPath' as the key. If you post your jQuery code that is sending the request I may be able to spot the issue.

**Comment by Holomew** [comment]
Finally able to get back to this...
So I tried a stripped-down version. No jquery, just plain javascript. Using your tag read as such:

    xhttp.open("POST", "py/tagRead", true);
    xhttp.setRequestHeader("Content-type", "text/plain");
    xhttp.send({"tagPaths":["path/here/tagName1", "samePath/here/tagName2"]});

And I get:

    HTTP ERROR 500
    Problem accessing /.../py/tagRead. Reason:

    Traceback (most recent call last):
    File .../py/tagRead:doPost>", line 2, in doPost
    TypeError: list indices must be integers

I also tried stringify-ing the path first and setting it to a variable but I can't seem to get python to like that list format that's being sent.

**Comment by Holomew** [comment]
Looks like a simple formatting error all along. Glad to get a POST working. Just needed some quotes on the string to send: 

`xhttp.send('{"tagPaths":["path/here/tagName1", "samePath/here/tagName2"]}');`

Thanks for your help!

**Comment by JoshMcguigan** [comment]
Ah yes, that is the `Content-Type: text/plain`. Glad you were able to figure it out. I believe that is a limitation in how Ignition handles the incoming data, but if you are able to find a workaround to allow `Content-Type: application/json` I'd happily accept a pull request.

**Comment by Holomew** [comment]
Do you know if Ignition provides a way to capture any more data besides the tag's value, quality, and timestamp? It would be great to get the other tag key/values.

**Comment by JoshMcguigan** [comment]
I believe they do. I'd start by looking at the scripting docs, as well as searching through the forums. You'd also have to modify the web scripts if you are trying to expose that additional data.

https://docs.inductiveautomation.com/display/DOC79/Scripting+Functions

**Comment by Holomew** [comment]
Thank you. According to their documentation, you can simply use dot notation to append for a value: 

qv = system.tag.read("[default]EastSection/ValveG/HOA_bit.EngHigh")
